
employee:
  path: /employee
  controller: App\Controller\EmployeeController::findAll

delete_employee:
   path: /employee/delete/{id}
   controller: App\Controller\EmployeeController::delete_employee

create_employee:
   path: /employee/create
   controller: App\Controller\EmployeeController::create_employee

employee_by_id:
  path: /employee/{id}
  controller: App\Controller\EmployeeController::employee_by_id

update_employee:
  path: /employee/update/{id}
  controller: App\Controller\EmployeeController::update_employee
